package HibernateTestCode;

// Generated 2015-4-28 15:53:06 by Hibernate Tools 3.4.0.CR1

/**
 * Names generated by hbm2java
 */

public class Names implements java.io.Serializable {

	private String name;
	private String country;
	private Integer value;

	public Names() {
	}

	public Names(String name) {
		this.name = name;
	}

	public Names(String name, String country, Integer value) {
		this.name = name;
		this.country = country;
		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
